### ISSUE TITLE
Failed to connect to AC after discovery

### ISSUE THREAD

**Issue by georgebancila** [deiger/AirCon#116]
Hello, I configured the add-on correctly. My ac is discovered, it found the IP address, the ip key and key id. But after that it only says
`E0628 12:22:00.556  notifier.py:121] Failed to connect to 192.168.1.213, maybe it is offline?`

Any ideas?

**Comment by nlarenti** [comment]
Also for me the same problem. The problem is solved temporarily (a few hours / day) by cutting off the power to the air conditioner, and then reappearing.

**Comment by revoluta** [comment]
Hello, i have the same problem, It has been working correctly for a long time but since yesterday it gives me the same error message, I have rebooted, but the problem remains

**Comment by nlarenti** [comment]
If you are interested, I notice that all the wifi cards of my 4 air conditioners have door 80 closed.

**Comment by georgebancila** [comment]
For some reason it works for a few days now, I did nothing to it..

**Comment by giros79** [comment]
just have a look to the hi sense folder.
Should have 1 file for each AC.
Have a look to IP address and assign the same to the router (or change in the .json and assign the one from the router)
Let me know if it works
